build:
	@$(MAKE) $(MakeOptions) -C ../.. -f Makefile $(MAKECMDGOALS)
default:
	@$(MAKE) $(MakeOptions) -C ../.. -f Makefile $(MAKECMDGOALS)
clean:
	@$(MAKE) $(MakeOptions) -C ../.. -f Makefile $(MAKECMDGOALS)
